### PR TITLE
chore(legal): adds MIT license

### LINKED ISSUE #463: Project has no OSS License

### PR DESCRIPTION
**Pull request by petermetz**
License itself could be anything else you choose of course. Submitting with MIT because this is the one I always use when given a choice.

Fixes #463

### CODE REVIEW

**Comment by jcchavezs** [comment]
Hi @petermetz thanks for this. I recommend we instead align with the other openzipkin libraries and use apache:
- https://github.com/openzipkin/brave/blob/master/LICENSE
- https://github.com/openzipkin/zipkin-go/blob/master/LICENSE

**Comment by eirslett** [comment]
I guess somebody simply forgot to commit the license file. It's supposed to be Apache 2, like the other Zipkin repositories.

**Comment by adriancole** [comment]
agreed. supposed to be ASL 2. no idea how we forgot so long :D

**Comment by petermetz** [comment]
@eirslett @adriancole @jcchavezs 
Swapped it out to Apache 2.0, let me know if anything else is not cool. I just need it to have a legit license so I can use the project. ;-)


Not strictly related to this PR: While I was looking at the brave license file you linked I saw this (copyright info missing):
https://github.com/openzipkin/brave/blob/739a458dd5a20e8f0a57fb2b0a1d37998a038503/LICENSE#L189

**Comment by jcchavezs** [comment]
Care to open a PR in brave?

man. 27. jan. 2020, 19:19 skrev Peter Somogyvari <notifications@github.com>:

**Comment by jcchavezs** [comment]
Thanks a lot @petermetz

**Comment by petermetz** [comment]
> Care to open a PR in brave? 

Sure: https://github.com/openzipkin/brave/pull/1068

**Comment by adriancole** [comment]
ps ASL license text being literally copied has an advantage which is that it matches checksums with other projects and people don't have to do diffs on basis of the template. I don't think there's any reason for us to change the explanation section of the ASL text, we just need to apply the rules appropriate in our files which use the headers. ex this is one version of the ASL file which is indeed templated https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by jcchavezs** [comment]
Good explanation @adriancole. Given that we are tackling this, do you think
we should use the same approach as brave and add license headers on the
files?

tir. 28. jan. 2020, 02:17 skrev Adrian Cole <notifications@github.com>:

**Comment by adriancole** [comment]
possibly?

apache foundation has a short version they use in javascript files (to avoid assets being huge)

> Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements; and to You under the Apache License, Version 2.0.

https://www.apache.org/legal/src-headers.html#is-a-short-form-of-the-source-header-available

We could have something small like that if we desired, like..
> Copyright 2020 Copyright 2019 The OpenZipkin Authors; licensed You under the Apache License, Version 2.0.

I know that in our UI, we use the longer form headers, which we could also do here.

cc @openzipkin/core

**Pull request merged**
