### PR TITLE
Fix incorrect span durations when using hapi.js middleware

### LINKED ISSUE #61: Span durations appear to be incorrect for hapi.js middleware
Lengthy requests exceeding several seconds are being reported as 1-2ms. 

Wrote a failing test here: https://github.com/zackangelo/zipkin-js/blob/fix_hapi_span_duration/packages/zipkin-instrumentation-hapi/test/integrationTest.js#L157

Has anyone else noticed this? If so, or seems entirely possible, will open a PR to fix.

### PR DESCRIPTION
**Pull request by zackangelo**
Fixes #61. 

Not sure if what I'm doing here is okay. In order to split the span actions into two callbacks, I'm storing the trace on the request object and then reattaching it to the context in the response hook. 

@adriancole @eirslett

### CODE REVIEW

**Comment by zackangelo** [comment]
Fixing linter errors.

**Comment by zackangelo** [comment]
Seems that using the `.plugins` hash on the request object is the correct way for a middleware to inject request state onto the object.

> plugins - plugin-specific state. Provides a place to store and pass request-level plugin data. The plugins is an object where each key is a plugin name and the value is the state.

**Comment by sveisvei** [comment]
Looks good to me. 

Indeed @zackangelo , seems that `request.plugins` is the convention for appending data from plugins.

**Comment by zackangelo** [comment]
:warning: Please don't merge yet, may have found an issue.

**Comment by zackangelo** [comment]
Moved the `reply.continue` call into `tracer.scoped` to keep the continuation chain in tact. Also, some versions of hapi were complaining about the `response.on('finish'...)` event hook so I'm just calling it in `onPreResponse` directly now (which seems to match other instrumentations more closely as well).

**Comment by adriancole** [comment]
so good to go?

**Comment by adriancole** [comment]
thanks @zackangelo

**Pull request merged**
