### PR TITLE
Fix: Binary annotation cannot be array (must be string)

### PR DESCRIPTION
**Pull request by pbadenski**
In #116 I made an unfortunate error and passed an array to recordBinary.. This will create an erroneous trace, which cannot be sent to zipkin.

### CODE REVIEW

**Comment by adriancole** [comment]
We have a failing test on redis due to possibly a different change. Are you able to have a look and help fix that broken window?

**Comment by pbadenski** [comment]
Will do.

**Comment by pbadenski** [comment]
It was my fault entirely! Fixed :D

**Comment by adriancole** [comment]
thanks!

**Pull request merged**
