### PR TITLE
Fix null reference error in BatchRecorder when terminating a span tha…

### PR DESCRIPTION
**Pull request by spoulson**
…t has been expired.

### CODE REVIEW

**Comment by spoulson** [comment]
AppVeyor build fails on unrelated unit test.  They all pass for me locally.

**Comment by eirslett** [comment]
I don't like the architecture of the existing code... this is a patch that fixes the problem, but I'm not sure _writeSpan() should handle things like non-existing spans... it's a violation of the single responsibility principle. @adriancole do you think it's possible to make some more invasive refactoring in this file?

**Comment by adriancole** [comment]
@eirslett yep certainly we can. agreed that writing the span should be on something that is in fact a span at the time :)

**Comment by rooftopsparrow** [comment]
This is affecting me as well, is there a previous version that isn't affected by this ?

**Comment by adriancole** [comment]
I added a TODO to follow-up on the refactor rather than block the fix

**Comment by adriancole** [comment]
0.11.2

**Comment by spoulson** [comment]
🎉

**Pull request merged**
