### PR TITLE
chore(#338): Removes support for node 6 in travis.

### PR DESCRIPTION
**Pull request by jcchavezs**
Comes from #338 

Ping @openzipkin/zipkin-js-champions

### CODE REVIEW

**Comment by eirslett** [comment]
LGTM! :shipit:

**Comment by ghermeto** [comment]
Hi @jcchavezs,

this looks good but does not solve #338 completely. To make sure people know the support for node 6 was dropped, we should add a [engines field in package.json](https://docs.npmjs.com/files/package.json#engines).

Would you like me to take care of that on a different PR?

**Comment by jcchavezs** [comment]
True, this is just the first step to unblock those PRs being stucked
because of node 6 support on CI.

I have a question regarding engines: will this work with browser tests and
browse usages? If that is OK please go ahead with the PR.

Ping @BenoitZugmeyer @ewhauser

Den man. 18. mar. 2019, 20:14 skrev Guilherme Hermeto <
notifications@github.com>:

**Comment by ghermeto** [comment]
the `engines` field should not affect either. It is only meant for `node`.

**Comment by jcchavezs** [comment]
I see. Go ahead with the PR!

Den man. 18. mar. 2019, 20:34 skrev Guilherme Hermeto <
notifications@github.com>:

**Comment by jcchavezs** [comment]
This will address https://github.com/openzipkin/zipkin-js/issues/231

Den man. 18. mar. 2019, 20:50 skrev José Carlos Chávez <jcchavezs@gmail.com

**Pull request merged**
