### PR TITLE
Feature/babel 7

### PR DESCRIPTION
**Pull request by DavideCarvalho**
- Changed babel-preset-es2015 to @babel/preset-env (es2015 is deprecated and doesn't work anymore)
- Added script "install:deps" to install the dependencies on every package
- Changed global test script to "lerna run test". Looks like babel 7 has a problem with monorepo, so we have to trigger the tests on every package now
- Added .babelrc to the packages too

### CODE REVIEW

**Comment by DavideCarvalho** [comment]
image
This is the error that i'm getting when trying to build with babel 7, will give it a closer look once I get home

**Comment by jcchavezs** [comment]
Ping @mkante

**Comment by DavideCarvalho** [comment]
Okay, looks like Babel 7 does not run on node 4.x

**Comment by DavideCarvalho** [comment]
I’m not being able to reproduce travis error locally. Can somebody try it too? The error is at zipkin-instrumentation-request-promise when we run the tests.

**Comment by jcchavezs** [comment]
Amazing @DavideCarvalho, would you mind rebasing this PR? We can wait until tomorrow to see if we get some feedback from people.

**Comment by DavideCarvalho** [comment]
Rebased and everything seems to be working. Okay, we'll wait until tomorrow then.

**Comment by jcchavezs** [comment]
Awesome! Let's wait until tomorrow :).

Den lør. 17. nov. 2018, 15:17 skrev Davi de Carvalho <
notifications@github.com:

**Comment by jcchavezs** [comment]
@DavideCarvalho sorry we merged something and now you need to rebase. After you rebase I will just merge it.

**Comment by DavideCarvalho** [comment]
Okay, i took off test:ts from the test script and it passed, i'll take a look on it

**Comment by DavideCarvalho** [comment]
This is the error I'm getting with test:ts on ci. Does anybody know what is this?
image

**Comment by DavideCarvalho** [comment]
Locally I'm getting this error:
```
i ts-runtime v0.1.35
× error TS6053: File 'C:/Users/davi_/Documents/programacao/zipkin-js/packages/zipkin/test-types.ts' not found.
× Processing was interrupted.
```

**Comment by DavideCarvalho** [comment]
I was giving a look at ts-runtime, the docs doesn’t say anything about finding files with globs - using *.ts -.

**Comment by jcchavezs** [comment]
Any idea @sonybinhle?

**Comment by sonybinhle** [comment]
@DavideCarvalho @jcchavezs Maybe we need to install chai and mocha types definitions otherwise ts-runtime couldn't understand the syntax of the tests.

`yarn add @types/chai  @types/mocha --dev -W`

I tried it and the tests run locally.

**Comment by DavideCarvalho** [comment]
Okay, I’ll make this change and push it again

**Comment by DavideCarvalho** [comment]
Okay, after the types everything worked fine. Ready to merge @jcchavezs

**Comment by jcchavezs** [comment]
Thanks a lot @DavideCarvalho. Great work!

**Pull request merged**
