### PR TITLE
Fix tracer context for zipkin-instrumentation-request

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
httpclient.recordResponse must be called inside of tracer.scoped otherwise it mutates the current context. This causes spans to have the wrong parent. 

This pattern is used in the other packages already [restInterceptor](https://github.com/openzipkin/zipkin-js/blob/a8ab73d26157a3b25b207425e2808ee39105afa1/packages/zipkin-instrumentation-cujojs-rest/src/restInterceptor.js#L29-L31), [express](https://github.com/openzipkin/zipkin-js/blob/001306fc9bbd017553be8b9db84f322efdebbe20/packages/zipkin-instrumentation-express/src/expressMiddleware.js#L54-L61), [connect](https://github.com/openzipkin/zipkin-js/blob/55f461eb14753658fdb3f64cab883d8668f31b4c/packages/zipkin-instrumentation-connect/src/middleware.js#L67)

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks @chris-smith-zocdoc for this improvement. @ghermeto do you have any input on this?

**Comment by ghermeto** [comment]
I will look into this...

**Comment by chris-smith-zocdoc** [comment]
Thanks @ghermeto, let me know if you have any questions for me

**Comment by jcchavezs** [comment]
Merging this for now. @ghermeto if any further we just raise an issie.

**Pull request merged**
