### PR TITLE
Fix ServerAddr UInt8Array to Buffer for thrift

### LINKED ISSUE #99: Scribe transport throws when given an Annotation.ServerAddr
By applying this patch to the test in zipkin-transport-scribe 

```patch
diff --git a/packages/zipkin-transport-scribe/test/integrationTest.js b/packages/zipkin-transport-scribe/test/integrationTest.js
index 6a0179c..2c269fa 100644
--- a/packages/zipkin-transport-scribe/test/integrationTest.js
+++ b/packages/zipkin-transport-scribe/test/integrationTest.js
@@ -46,6 +46,7 @@ describe('Scribe transport - integration test', () => {
           flags: 0
         });
         tracer.setId(id);
+        tracer.recordAnnotation(new Annotation.ServerAddr({serviceName: 'test'}));
         tracer.recordAnnotation(new Annotation.ClientSend());
         tracer.recordAnnotation(new Annotation.ClientRecv());
         setTimeout(() => {
```

I get this error: 

```
  Scribe transport - integration test
    1) should send trace data to Scribe

  1) Scribe transport - integration test should send trace data to Scribe:
     Uncaught TypeError: buf.copy is not a function
      at /dev/zipkin-js/node_modules/thrift/lib/nodejs/lib/thrift/buffered_transport.js:164:9
      at Array.forEach (native)
      at TBufferedTransport.flush (/dev/zipkin-js/node_modules/thrift/lib/nodejs/lib/thrift/buffered_transport.js:163:19)
      at TBinaryProtocol.flush (/dev/zipkin-js/node_modules/thrift/lib/nodejs/lib/thrift/binary_protocol.js:43:21)
      at serializeSpan (/dev/zipkin-js/packages/zipkin/lib/serializeSpan.js:21:12)
      at queue.forEach.span (src/ScribeLogger.js:19:43)
      at Array.forEach (native)
      at scribeClient.open.err (src/ScribeLogger.js:18:24)
      at .<anonymous> (/dev/zipkin-js/node_modules/scribe/lib/scribe.js:110:7)
      at Socket.<anonymous> (/dev/zipkin-js/node_modules/scribe/node_modules/thrift/lib/thrift/connection.js:52:10)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:10)
```

The error occurs on the latest package version on latest node v7 and v6.

**Update**:

I did more debugging on this and found a UInt8Array in the span that the thrift library expects to be a Buffer with the copy method.

I changed the offending line and it no longer fails.

```
diff --git a/packages/zipkin/src/internalRepresentations.js b/packages/zipkin/src/internalRepresentations.js
index 1d3ee71..379abfa 100644
--- a/packages/zipkin/src/internalRepresentations.js
+++ b/packages/zipkin/src/internalRepresentations.js
@@ -91,8 +91,7 @@ function Address({key, endpoint}) {
   this.endpoint = endpoint;
 }
 Address.prototype.toThrift = function toThrift() {
-  const value = new Uint8Array(1);
-  value[0] = 1;
+  const value = Buffer.from([1]);
   const res = new thriftTypes.BinaryAnnotation({
     key: this.key,
     value,
```

Pull Request inbound!

### PR DESCRIPTION
**Pull request by rooftopsparrow**
Fixes #99

### CODE REVIEW

**Comment by rooftopsparrow** [comment]
Thanks for reviewing my PR 👍  Any ETA on getting this merged?

**Comment by adriancole** [comment]
how bout now? :)

**Comment by rooftopsparrow** [comment]
Curious what the release schedule is for the project? Any chance this gets published soon?

**Comment by adriancole** [comment]
>
> Curious what the release schedule is for the project? Any chance this gets
> published soon?
>
we have a nag-driven release schedule :) better than arbitrary releases w/o
demand IMHO

0.7.1 is now out!

**Comment by rooftopsparrow** [comment]
Thanks so much!

**Pull request merged**
