### PR TITLE
Allow host to be overridden in httpServer instrumentation (#236)

### PR DESCRIPTION
**Pull request by rcoedo**
Link to the issue: https://github.com/openzipkin/zipkin-js/issues/236

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks for doing this @rcoedo. Would you mind to add tests for this?

**Comment by rcoedo** [comment]
Not at all, I will update the PR as soon as possible.

**Comment by jcchavezs** [comment]
Awesome work @rcoedo I am only concerned on not being breaking the default behavior. Can we cover it with a test as well? 

After that I believe we are ready to merge. Any feedback @adriancole?

**Comment by rcoedo** [comment]
@jcchavezs I'm afraid the test would be dependent on the host ip if I try to check the `LocalAddr` annotation ip address, and if I don't then the test will only check that the instrumentation records a `LocalAddr` annotation, just like all the other tests that we have.

We can't mock the "network-address" library with our current tooling, can we? Any other ideas? 😄

**Comment by rcoedo** [comment]
Maybe it is a bit ugly to query the OS as a side effect of instantiating a `LocalAddr` annotation, but I'm not sure about the implications of moving this behaviour out of it. I guess it would be a breaking change if users are instantiating LocalAddr annotations explicitly.

**Comment by jcchavezs** [comment]
I think it is good enough for now if we test that the annotation is there. This will guarantee that the flow is not breaking if we don't pass the parameter. Does it make sense to you?

**Comment by rcoedo** [comment]
This was is already being done by literally every other test but it is fine with me 👍 

If you have any other thoughts or suggestions just let me know! 😄

**Comment by jcchavezs** [comment]
Great work!

**Pull request merged**
