### PR TITLE
TypeScript Port

### PR DESCRIPTION
**Pull request by DavideCarvalho**
Starting to port zipkin codebase from JavaScript to TypeScript.

Must do:
- [ ] Port all zipkin packages
- [ ] Fix TSLint errors (maybe we should see what rules make sense to us and disable what we don't want)
- [ ] Fix tests errors

### CODE REVIEW

**Comment by DavideCarvalho** [comment]
Referencing #283

**Comment by DavideCarvalho** [comment]
What I could see from the tests i've made is that the build is ok, but the tests are breaking because ```require``` resolutes only to ```.js``` files. In order to get ts files, we need to explicitly tell the extension in the end, e.g ```require('./INetAddress.ts')```.
We can try to change to ```import``` and ```export```. Either way, we'll need to refactor the code.

**Comment by eirslett** [comment]
Looks like a good step is to rename all `.js` files to `.ts`, and run TypeScript with a loose/liberal config - then we can tighten it once more files are typed correctly?

Maybe we could run tests with ts-node? https://github.com/TypeStrong/ts-node

**Comment by DavideCarvalho** [comment]
The tests are running well with mocha and babel, I don't think ts-node will be needed. The only problem is with requiring files, since require tries to find .js files by default, and to require .ts files we need to put the extension along with the file name.

**Comment by DavideCarvalho** [comment]
When I get home I will change the require statements and test it with zipkin package.

**Comment by DavideCarvalho** [comment]
Strange, locally the tests are passing, while on CI it's getting ```../../node_modules/@types/node/index.d.ts(7265,88): error TS2304: Cannot find name 'Symbol'.```.

**Comment by eirslett** [comment]
> trange, locally the tests are passing, while on CI it's getting ../../node_modules/@types/node/index.d.ts(7265,88): error TS2304: Cannot find name 'Symbol'..

Old node.js version?

**Comment by DavideCarvalho** [comment]
I was using node 11, I changed to 6 and it still passes locally.

**Comment by jcchavezs** [comment]
Weird, anything you see @sonybinhle?

Den ons. 21. nov. 2018, 16:12 skrev Davi de Carvalho <
notifications@github.com:

**Comment by jcchavezs** [comment]
Thanks @sonybinhle if that is the case, can we do that in a separated PR so
we integrate the change earlier? What do you think @DavideCarvalho?

José Carlos Chávez


Den tor. 22. nov. 2018 kl. 15:24 skrev Binh Le <notifications@github.com>:

**Comment by sonybinhle** [comment]
> if that is the case, can we do that in a separated PR so we integrate the change earlier

Another way of solving it is by removing `"typescript": "^2.4.2"` from `packages/zipkin/package.json`. The global one is `"typescript": "^2.9.2"` seems to work fine with new `tsconfig.json`.

Another observation is that `tsc index.d.ts` is only be included in `packages/zipkin/package.json` but not on the other sub-packages. So maybe our purpose here is checking the packages/zipkin/index.d.ts` is valid with typescript version 2.4.2 

I think we should remove local typescript version and upgrade global typescript if it doesn't hurt any usages.

**Comment by eirslett** [comment]
Let's just go for latest TypeScript (v3.1) everywhere. There's no need for backwards compatibility since this will be v1.0.

**Comment by DavideCarvalho** [comment]
Oh, I have TS installed globally, maybe it's because of this it was working on my machine. Okay, i'll update TS version and try again

**Comment by jcchavezs** [comment]
@DavideCarvalho we merged a couple of PRs that are going to be part of the last 1.0. Could you please rebase your PR accordingly?

**Comment by DavideCarvalho** [comment]
```Error: Cannot find module './option.ts'```, I tried looking finding where is calling 'options.ts' but I couldn't debug it to the root of the problem. Something at ```packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js``` is calling a option.ts file.

First I thought that inside zipkin's lib folder was something calling a ```options.ts``` file, but I couldn't find.

**Comment by jcchavezs** [comment]
I see a pattern here and this is totally on me. I should have foreseen this before.

Zipkin JS is getting a lot of attraction these days and we get [more and more PRs every day](https://github.com/openzipkin/zipkin-js/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+sort%3Acreated-desc+language%3Ajavascript+merged%3A%3E2018-11-01+) (13 merged the last two weeks).

This PR has been created 6 days ago and since then we merged 8 PRs, every time we merge a new PR @DavideCarvalho has to do a rebase and with that there is a risk new stuff come up. This is definitively not desired, efficient nor fair and it can get him burned out.

On the other hand, we can not just merge keep those PRs hanging until we finish this titanic work (which I will be in debt with @DavideCarvalho and all you guys for a while) as this is mainly a volunteer project and 4 months ago it was almost dead so we want contributors to be proactive and open PRs to solve issues but we also want to fulfill our part of the treat by getting stuff merged and released ASAP.

In that direction I see the future of this PR (if we keep the same behaviour) becoming so complex and error prone because every time the scope of the PR becomes endless that it is in risk of not getting to the goal.

My proposal is:
1. We instead of moving JS files into TS files, do that but into a folder called `packages-ts` but we test both on CI.
2. Every time someone a new PR we request them to do the counter part in packages-ts (being a blocking rule)
3. We keep releasing 0.x versions of zipkin but don't make `packages-ts` official.
4. Once the move to TS is done we just drop the JS (which should be the same).

This approach has many advantages:
1. We can move one by one the packages independently (smaller PRs merged more often)
2. Every change in js files have a counter part in TS done by the contributors.
3. We don't block @DavideCarvalho anylonger.
4. Someone else can help him.

What do you think peeps? @openzipkin/zipkin-js-champions @eirslett @ghermeto 

Any other idea that help us to integrate this changes earlier without breaking existing clients will be also considered.

**Comment by eirslett** [comment]
I suggest a "simple" solution:

We rename every .js file to .ts, set up a build script (noop-ing, just using babel removing type annotations) and then we merge that PR right away.
Remember, all JavaScript is still valid TypeScript, so it won't break anything.

There won't be any merge conflicts or need to do double work.

The technique is called gradual typing, and means that the types are opt-in instead of mandatory.

We configure the TypeScript validator to be very liberal (we might even simply disable it for now!)

Moving forward, we must make sure all TypeScript-related branches are very short-lived, so they don't collide with other incoming pull requests. Therefore, every TypeScript-PR must also be kept minimal, and there must be emphasis on reviewing and merging them quickly (time-wise).

**Comment by DavideCarvalho** [comment]
I agree with the gradual typing, and it’s what I’m aiming with this PR, but I’m getting some errors on the ci and are errors that I’m not getting locally, don’t know why. If someone could test it locally as well, I could make the change and see if it passes. I’lol try again at home hoping to catch those errors to debug

**Comment by ghermeto** [comment]
@jcchavezs this is a classical migration issue. Usually the solution is to focus on small verticals. Fortunately `zipkin-js` provides a easy and unique opportunity for that: it is all split into smaller packages

You don't need to add typing is all packages or even rename files in all packages. You can start with renaming the packages on the most important package: `zipkin` and from there hit the transports, context and later the interceptors.

Honestly I don't even see a reason for the packages that will run only in `node.js` to be transpiled at all (IMO it is only good to make production debugging a nightmare). Of course you want some consistency, but that can be eventually achieved (and if makes sense)...

For that to work though, you can't wait until `1.0`. You have to merge the PRs as they arrive.

**Comment by jcchavezs** [comment]
@ghermeto thanks for the insight. @DavideCarvalho maybe @sonybinhle can help you?

**Comment by sonybinhle** [comment]
@DavideCarvalho After the build, the bundle is in the **lib** folder. `"@babel/preset-typescript"` transpile `const option = require('./option.ts');` to `var option = require('./option.ts');` instead of `var option = require('./option');`.

We could replace all required `.ts` extensions with **empty** after building by a `script` or we could find any existing babel plugins to do that job for us. The alternative solution could be removing all `.ts` required extension from typescript files since having `require('xxxx**.ts**')` may be unnecessary.

**Comment by DavideCarvalho** [comment]
I find it very strange, since nothing inside ```lib``` folder is calling for a ```.ts``` file.

**Comment by sonybinhle** [comment]
@DavideCarvalho Maybe you have some global config that removes `.ts` extension. The result if I run build in my computer.

screen shot 2018-11-28 at 11 31 22 am

**Comment by DavideCarvalho** [comment]
Okay, I guess this branch is just too far behind and is quite hard to rebase, so I will create another branch to finish this task.
Instead of doing ```require(file.ts)```, looks like ```import``` and ```export``` statements are transpiled without the file extension, so I guess using them will be easier, I'll do it on zipkin package first.

**Comment by DavideCarvalho** [comment]
I changed two imports on index.ts file and it worked! Build and tests are running, I'll push it here to see how the ci will behave

**Comment by jcchavezs** [comment]
We did not have much activity on this lately so I am closing for now. Please feel free to reopen it whenever you can continue the great work @DavideCarvalho!

**Pull request closed without merging**
