### PR TITLE
Update hapi plugin to use v17

### PR DESCRIPTION
**Pull request by PaulinaStypinska**
Hey there,

So I finally got around to doing this. This unfortunately does introduce a breaking change (since Hapi v17 does so as well). All tests and linting pass.

If there's anything else I can do, let me know pls.

### CODE REVIEW

**Comment by adriancole** [comment]
@unindented @zackangelo @rexxars @pbadenski -- can one of you be an awesome person to an awesome person by reviewing this PR and weighing in if a bump to strictly hapi 17 is alright?

**Comment by adriancole** [comment]
so the node 4 and 6 builds failed on

"error hapi@17.3.1: The engine "node" is incompatible with this module. Expected version ">=8.9.0".
error Found incompatible module"

**Comment by adriancole** [comment]
So, we need a way to have certain modules opt-out of node.js versions if we retain support of node 4 and 6

**Comment by jcchavezs** [comment]
@fbaiodias could you please give some input on this one?

**Comment by jcchavezs** [comment]
@PaulinaStypinska can you please explain what will be breaking? Also, would you mind to do a rebase?

**Comment by jcchavezs** [comment]
@PaulinaStypinska We dropped support for node4 and we might do the same for node 6. Would update your PR only supporting node 8?

**Comment by jcchavezs** [comment]
There is this PR BTW: https://github.com/openzipkin/zipkin-js/pull/337/files

**Pull request closed without merging**
