### PR TITLE
update libraries and scripts

### PR DESCRIPTION
**Pull request by ghermeto**
Reasoning: `zipkin-js` dev dependencies are far behind. 
This commit mainly updates `mocha` and `lerna`.

### CODE REVIEW

**Comment by ghermeto** [comment]
I really don't know what happened with TravisCI... I made sure it would pass on my fork first:
https://travis-ci.org/ghermeto/zipkin-js/builds/460622168

**Comment by jcchavezs** [comment]
@ghermeto it was a flickering test. What worries me is the alert from sync:

https://app.snyk.io/org/openzipkin/test/github/6a76c7f4-7ca8-4a9d-9ce9-33ceb64ba958/master..0db32ccf720f403d530af2438fb99833a508ac50?fromStatus=true

image

Any input @openzipkin/zipkin-js-champions?

**Comment by ghermeto** [comment]
thanks @jcchavezs, I'm not authorized to see the `Snyk` test. The worst part is that I updated `lerna` because I ran `npm audit` and it complained about `lerna 2.11` and now `npm audit` was passing. Maybe we should contact the lerna maintainers?

can we move `lerna` and ` yarn` to `dev-dependency`? Does `zipkin-js` really needs them in production?

**Comment by jcchavezs** [comment]
I don't think we needed for prod so I am OK moving it to dependencies-dev. I am also OK to merge this PR if npm audit validates this.

**Comment by ghermeto** [comment]
updated! running `yarn audit` `yarn run audit` and `npm audit` on my command line, this is what I get:
```bash
ghermeto:zipkin-js [audit_fix]$ yarn run audit
yarn run v1.12.3
$ lerna exec npm audit
lerna notice cli v3.5.1
lerna info Executing command in 18 packages: "npm audit"
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2379 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2381 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2539 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2502 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2384 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2653 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2513 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2505 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2394 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2385 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2384 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2482 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 3258 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2569 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2550 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2535 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2393 scanned packages
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 2546 scanned packages
lerna success exec Executed command in 18 packages: "npm audit"
✨  Done in 7.37s.
ghermeto:zipkin-js [audit_fix]$ yarn audit
yarn audit v1.12.3
0 vulnerabilities found - Packages audited: 42149
✨  Done in 1.34s.
ghermeto:zipkin-js [audit_fix]$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 42382 scanned packages
```

**Comment by adriancole** [comment]
many thanks

**Pull request merged**
