### PR TITLE
fix problem with skipping some messages in HttpLogger.js

### PR DESCRIPTION
**Pull request by struhtanov**
The problem: if some messages are added to queue while pushing to zipkin, they will be lost.

### CODE REVIEW

**Comment by eirslett** [comment]
LGTM

**Comment by sveisvei** [comment]
Nice bugfix!

**Comment by doochik** [comment]
@sveisvei @eirslett 
Hi guys! Could you merge this fix please? I've affected with this issue.

**Comment by adriancole** [comment]
0.7.2 on the way. thanks!

**Comment by doochik** [comment]
Thanks a lot!

**Pull request merged**
