### PR TITLE
Use isomorphic-fetch instead node-fetch

### PR DESCRIPTION
**Pull request by tonypizzicato**
Use isomorphic-fetch instead node-fetch for better browser support

### CODE REVIEW

**Comment by eirslett** [comment]
Sounds like a good idea.
Is it possible to test this in a browser? Maybe we should add karma configuration to the project, and run browser tests in PhantomJS?

**Comment by adriancole** [comment]
>
> Is it possible to test this in a browser? Maybe we should add karma
> configuration to the project, and run browser tests in PhantomJS?
>
agreed. while extremely tempting to not add tests or punt to a future PR,
this is how tests don't end up backfilled despite best intentions. If you
can, please be a zipkin-js hero and try to test this!

**Comment by adriancole** [comment]
ping back if this is a help-wanted type of status. Maybe someone can point to a similar project which is setup to do browser testing with PhantomJS

**Comment by adriancole** [comment]
soo.. should we merge w/o test or ...

**Comment by adriancole** [comment]
closing but will happily re-open when interest resumes

**Pull request closed without merging**
