### PR TITLE
Add timer to prevent node process to exit too early before sending spans

### PR DESCRIPTION
**Pull request by ocastx**
fixes openzipkin/zipkin-js#33

### CODE REVIEW

**Comment by eirslett** [comment]
How would it look if we implemented process.on('exit', flushQueue) or something like that? It would be a little more explicit. My gut feeling is that registering an empty noop-timeout to fix the issue is a little brittle. E.g. one could imagine a JavaScript runtime engine discovered it was an empty callback/noop and it would "optimize" away the whole timeout, which would ruin this fix.

**Comment by ocastx** [comment]
I get what you are saying, but I would suggest rather than using `process.on('exit', flushQueue)` to use a mechanism to schedule a timeout only if there are spans in the queue instead of using an interval at all. 

For example we could then schedule a timeout always when a new span is added to the queue, except if there is already a timer running. Then, if nothing is in the queue the timer would not be running and the interval would not use any cycles. Thereby we would not have a problem with a noop-timeout, an interval that is not executed when the process is terminated and have a more explicit way when the queue is about to be flushed.

**Comment by jquatier** [comment]
I think that would definitely work. Unfortunately only synchronous operations can be put in process.on('exit'), so the process would still exit before the aync http execution ran.

**Comment by adriancole** [comment]
Is there any way to automatically test this sort of behavior? (ex in the
java project, we have things that literally start/stop processes, though
not for this purpose)

**Comment by eirslett** [comment]
> Unfortunately only synchronous operations can be put in process.on('exit')

Looks like `process.on('beforeExit', ...)` supports async calls, like for this use case.

> schedule a timeout only if there are spans in the queue instead of using an interval at all.

I guess in a shutdown hook, this could be implemented as a simple if-check? Only flush the queue if there are spans in there?

> have a more explicit way when the queue is about to be flushed.

Can you please explain a bit more how it would be more explicit? In my mind, adding a process shutdown hook is more explicit, since it's code that is supposed to be run when the process shuts down. But I don't have the complete picture in my mind...

Also, is this issue HTTP-specific, or does it also count for kafka and scribe? I would imagine that they suffer from the same problem, and that the fix would be similar. So it could maybe be refactored to work across all transports?

**Comment by ocastx** [comment]
> Looks like process.on('beforeExit', ...) supports async calls, like for this use case.

Sounds like a good solution. Only problem with `beforeExit` is, that it's only triggered when the event loop is empty and the node process is about to exit. Therefore, when the process exits due to an exception the hook will not be triggered and the spans not send.
We can also use `process.on('uncaughtException', ...)` additionally to catch this case too.

> Also, is this issue HTTP-specific, or does it also count for kafka and scribe? I would imagine that they suffer from the same problem, and that the fix would be similar. So it could maybe be refactored to work across all transports?

Yes, I think the other transports would benefit from this refactor too.
I can update the PR if all can agree to use hooks to solve this.

**Comment by eirslett** [comment]
> We can also use process.on('uncaughtException', ...) additionally to catch this case too.

I think uncaughtException only allows synchronous handlers? "The correct use of 'uncaughtException' is to perform synchronous cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process." https://nodejs.org/api/process.html#process_event_uncaughtexception

A reasonable fallback for synchronous handling of uncaughtException would be to check if there are any spans in the queue that are not sent, and then console warn that x number of spans were not sent. Or something like that?

**Comment by ocastx** [comment]
> A reasonable fallback for synchronous handling of uncaughtException would be to check if there are any spans in the queue that are not sent, and then console warn that x number of spans were not sent

Yes this would be a reasonable fallback but this wouldn't benefit data integrity. For the project I am currently working on this would not a be an appropriate solution because it would be necessary to deliver spans especially when the process is about to crash for better debugging.

**Comment by jquatier** [comment]
Unfortunately, I don't think there's much you can do in the uncaught exception case. The process is going to exit. Even the solution in this PR doesn't solve that and I think logging as @eirslett suggested is appropriate. We could ecen consider logging the actual spans left in the queue, so that you still have the span data in the logs to look at perhaps?

**Comment by adriancole** [comment]
ps BatchRecorder has a timeout bug caused by #3. Sending a fix shortly

**Comment by adriancole** [comment]
ps I made a time-based test here https://github.com/openzipkin/zipkin-js/pull/36
looking around, the easier library to do this is https://github.com/vesln/timekeeper

**Comment by ocastx** [comment]
You actually can do asynchronous operations in the uncaughtException hook. It is not recommend because the application is likely to be in an unknown state so you should not continue running it. 
We'll use this for our project to still send spans because this data is crucial but I can understand if you don't want this to be in the main project.

**Comment by eirslett** [comment]
> but I can understand if you don't want this to be in the main project.

If it's possible, then it would probably be desirable if it can be done as safely as possible. Could maybe be a configuration flag?

**Comment by ocastx** [comment]
I would prefer a configuration flag too if you guys are ok with it.

**Pull request closed without merging**
