### PR TITLE
Trades unused letChildId for letId

### PR DESCRIPTION
**Pull request by adriancole**
This adds letId which is a shortcut to combining tracer.scoped with
setId. It pays for the additional code by removing an unused function:
tracer.letChildId

### CODE REVIEW

**Comment by adriancole** [comment]
versions will be sorted on release. `yarn test` does the right things in the mean time afaik

**Comment by adriancole** [comment]
we have a persistent issue in the node 4 tests which is behind the red

**Comment by mkante** [comment]
Cool thx

**Comment by adriancole** [comment]
@pbadenski do you have time to update the http instrumentation to use letId? I think it might be less errorprone, but could be wrong

**Pull request merged**
