### PR TITLE
Run tests on node 8

### PR DESCRIPTION
**Pull request by SimenB**
Will be LTS in October

### CODE REVIEW

**Comment by adriancole** [comment]
interesting.. one of the travis things died for lack of babel https://travis-ci.org/openzipkin/zipkin-js/jobs/272074828

**Comment by SimenB** [comment]
Might be an issue with npm 5. Would you be opposed to using yarn? Then bootstrapping would be quicker as well (bootstrap is supported by yarn directly)

**Comment by adriancole** [comment]
I'm up for whatev

**Comment by SimenB** [comment]
Pushed with yarn. Not sure about the appveyor changes, but let's see!

**Comment by adriancole** [comment]
all green.. lovely!

**Comment by SimenB** [comment]
(Windows and linux install instructions for yarn can be seen in this PR. mac users should do `brew install yarn`)

**Pull request merged**
